// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwMjo6s9x2WO-fsZKPz1j-lS44VALKGPM',
    appId: '1:207912333514:web:f73651dac763b856e90433',
    messagingSenderId: '207912333514',
    projectId: 'streetbuzz-07',
    authDomain: 'streetbuzz-07.firebaseapp.com',
    storageBucket: 'streetbuzz-07.firebasestorage.app',
    measurementId: 'G-EQZ5QD1S0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_n1I2i6Nj76Hs8twQXLp8QTvbkCRgM3Q',
    appId: '1:207912333514:android:48f1f1bee45718a4e90433',
    messagingSenderId: '207912333514',
    projectId: 'streetbuzz-07',
    storageBucket: 'streetbuzz-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj3YY3pnYQvW1vhZ-5TK1veGW1GIh95c0',
    appId: '1:207912333514:ios:dbfe468453dcea20e90433',
    messagingSenderId: '207912333514',
    projectId: 'streetbuzz-07',
    storageBucket: 'streetbuzz-07.firebasestorage.app',
    iosBundleId: 'com.example.streetbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj3YY3pnYQvW1vhZ-5TK1veGW1GIh95c0',
    appId: '1:207912333514:ios:dbfe468453dcea20e90433',
    messagingSenderId: '207912333514',
    projectId: 'streetbuzz-07',
    storageBucket: 'streetbuzz-07.firebasestorage.app',
    iosBundleId: 'com.example.streetbuzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwMjo6s9x2WO-fsZKPz1j-lS44VALKGPM',
    appId: '1:207912333514:web:14d8e6420298be3de90433',
    messagingSenderId: '207912333514',
    projectId: 'streetbuzz-07',
    authDomain: 'streetbuzz-07.firebaseapp.com',
    storageBucket: 'streetbuzz-07.firebasestorage.app',
    measurementId: 'G-1RMMEGQZ5N',
  );
}
