// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-JDVWv7GoBk3ogmMQysBatU1wVfPZScw',
    appId: '1:691348964439:web:dff671331b6c6ee8b08f12',
    messagingSenderId: '691348964439',
    projectId: 'tomato-8904c',
    authDomain: 'tomato-8904c.firebaseapp.com',
    storageBucket: 'tomato-8904c.firebasestorage.app',
    measurementId: 'G-RME5DE4N1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlwJ2dKGXwFbLnNVwo-XKv9maMVTtz0IE',
    appId: '1:691348964439:android:5cf3308d0555ffa3b08f12',
    messagingSenderId: '691348964439',
    projectId: 'tomato-8904c',
    storageBucket: 'tomato-8904c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6w11VIGu4fgYliRuIq8N-T_I89eTBGe8',
    appId: '1:691348964439:ios:88441e5dcd080b66b08f12',
    messagingSenderId: '691348964439',
    projectId: 'tomato-8904c',
    storageBucket: 'tomato-8904c.firebasestorage.app',
    iosBundleId: 'com.example.streetbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6w11VIGu4fgYliRuIq8N-T_I89eTBGe8',
    appId: '1:691348964439:ios:88441e5dcd080b66b08f12',
    messagingSenderId: '691348964439',
    projectId: 'tomato-8904c',
    storageBucket: 'tomato-8904c.firebasestorage.app',
    iosBundleId: 'com.example.streetbuzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-JDVWv7GoBk3ogmMQysBatU1wVfPZScw',
    appId: '1:691348964439:web:15325c8f504c291ab08f12',
    messagingSenderId: '691348964439',
    projectId: 'tomato-8904c',
    authDomain: 'tomato-8904c.firebaseapp.com',
    storageBucket: 'tomato-8904c.firebasestorage.app',
    measurementId: 'G-Y273F5D8QN',
  );
}
